AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Thumbnail Generator Lambda Function

Globals:
  Api:
    BinaryMediaTypes:
      - image/webp
      - multipart/form-data

Resources:
  ThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 30
      MemorySize: 128
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${InputBucketName}
        - S3CrudPolicy:
            BucketName: !Sub ${InputBucketName}
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref InputBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpg
        ApiEvent:
          Type: Api
          Properties:
            Path: /thumbnail
            Method: post

  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputBucketName

Parameters:
  InputBucketName:
    Type: String
    Description: Name of the S3 bucket
